title: Hello, world! I'm Tiárli Oliveira
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/tiarly.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tiárli Oliveira # add your name
author-img: tiarly.jpg # add your photo
about-author: I am a Sr backend engineer & Team Lead pashionate about Ruby. Always hungry to keep learning. # add description
social-twitter: tiarlioliveira
social-facebook: # add your Facebook handle
social-github: tiarly # add your Github handle
social-linkedin: tiarly
social-email: tiarlioliveira@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
